version: "2.2"
services:
  app:
      build: ./etc/php-fpm
      restart: always
      links:
        - redis
      expose:
        - 9000
      volumes:
          - "./:/var/www/app"
      command: bash -c "composer install --no-interaction -o && php-fpm"
  worker:
      build: ./etc/php-fpm
      restart: "no"
      links:
        - redis
      volumes:
          - "./:/var/www/app"
      command: bash -c "composer install --no-interaction -o && php artisan fibonacci:generate"
      mem_limit: 150M
      memswap_limit: 0M
      mem_reservation: 50M
      cpus: 0.05
      cpu_count: 1
      cpu_percent: 5
      cpu_shares: 73
  redis:
      image: redis:5-alpine
      expose:
        - 6379
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes --appendfsync always
      volumes:
        - redis-persistant-volume:/data

volumes:
  redis-persistant-volume:
